"""Schemas for employees and their compensation records."""

from datetime import date, datetime
from decimal import Decimal
from typing import Annotated, Literal

from pydantic import (
    AfterValidator,
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    model_validator,
)

from app.schemas.catalog import NonEmpty, ORMModel

Status = Literal["active", "on_leave", "terminated"]
# Termination is its own operation (POST /employees/{id}/terminate), never a plain field.
ActiveStatus = Literal["active", "on_leave"]
Money = Annotated[Decimal, Field(max_digits=14, decimal_places=2)]
CountryCode = Annotated[
    str, Field(min_length=2, max_length=2), AfterValidator(str.upper)
]
CurrencyCode = Annotated[
    str, Field(min_length=3, max_length=3), AfterValidator(str.upper)
]


class BasePayIn(BaseModel):
    """The employee's starting base pay, per the base-pay type's period (monthly)."""

    amount: Annotated[Money, Field(gt=0)]
    note: str | None = None


class EmployeeIn(BaseModel):
    """Create an employee. `code` is generated by the database; base pay is required
    and recorded as a "new hire" record effective on the hire date (FR-3)."""

    model_config = ConfigDict(extra="forbid")

    company_id: int
    first_name: NonEmpty
    last_name: NonEmpty
    email: EmailStr
    department_id: int
    job_title_id: int
    job_level_id: int
    current_country: CountryCode
    currency: CurrencyCode
    status: ActiveStatus = "active"
    hire_date: date
    base_pay: BasePayIn
    changed_by: NonEmpty


class EmployeeUpdate(BaseModel):
    """Edit employee details only. Compensation (FR-4), country and currency (FR-7),
    hire date and termination have their own operations, so they're rejected here."""

    model_config = ConfigDict(extra="forbid")

    company_id: int | None = None
    first_name: NonEmpty | None = None
    last_name: NonEmpty | None = None
    email: EmailStr | None = None
    department_id: int | None = None
    job_title_id: int | None = None
    job_level_id: int | None = None
    status: ActiveStatus | None = None


class TerminateIn(BaseModel):
    model_config = ConfigDict(extra="forbid")

    termination_date: date


class EmployeeOut(ORMModel):
    id: int
    code: str
    company_id: int
    first_name: str
    last_name: str
    email: str
    department_id: int
    department: str  # name
    job_title_id: int
    job_title: str  # name
    job_level_id: int
    job_level: str  # code
    current_country: str
    currency: str
    status: Status
    hire_date: date
    termination_date: date | None
    created_at: datetime
    updated_at: datetime


class CompensationRecordIn(BaseModel):
    """A compensation change for one type (FR-4). Any change reason works with any
    type ("correction" fixes a mistake); the effective date may be in the future.

    Country and currency aren't accepted: a record is written in the employee's
    current country and currency (the DB trigger enforces the currency)."""

    model_config = ConfigDict(extra="forbid")

    compensation_type_id: int
    change_reason_id: int
    effective_date: date
    amount: Decimal = Field(ge=0, max_digits=14, decimal_places=2)
    note: str | None = None
    changed_by: NonEmpty


class CompensationRecordOut(ORMModel):
    id: int
    employee_id: int
    compensation_type_id: int
    change_reason_id: int
    effective_date: date
    country: str
    currency: str
    amount: Decimal
    note: str | None
    changed_by: str
    created_at: datetime


class CompensationChangeOut(CompensationRecordOut):
    # False while the record is future-dated (it becomes current on its date), or
    # when a newer record of the same type is already current (a back-dated fix).
    is_current: bool


class DirectoryItem(BaseModel):
    id: int
    code: str
    first_name: str
    last_name: str
    email: str
    department_id: int
    department: str
    job_title_id: int
    job_title: str
    job_level_id: int
    job_level: str
    current_country: str
    status: Status
    hire_date: date
    currency: str
    total_compensation: Decimal | None  # annual CTC, employee's currency
    total_compensation_reporting: Decimal | None  # annual CTC, reporting currency


class DirectoryPageOut(BaseModel):
    items: list[DirectoryItem]
    next_cursor: str | None
    prev_cursor: str | None
    reporting_currency: str
    rates_as_of: dict[str, date]


class CurrentCompensationOut(BaseModel):
    compensation_type_id: int
    name: str
    category: str
    subtype: str | None
    period_months: int
    is_base_pay: bool
    counts_toward_total: bool
    record_id: int
    effective_date: date
    amount: Decimal  # per period_months, employee's currency
    annual_amount: Decimal
    annual_amount_reporting: Decimal | None


class HistoryItemOut(BaseModel):
    record_id: int
    compensation_type_id: int
    compensation_type: str
    effective_date: date
    country: str
    currency: str
    amount: Decimal
    previous_amount: Decimal | None
    percent_change: Decimal | None  # vs the previous record of the same type
    currency_changed: bool  # True: not comparable, the currency changed (FR-7)
    change_reason: str  # code
    change_reason_label: str
    note: str | None
    changed_by: str
    created_at: datetime


class ProfileOut(BaseModel):
    employee: EmployeeOut
    reporting_currency: str
    rates_as_of: dict[str, date]
    total_compensation: Decimal  # annual CTC, employee's currency
    total_compensation_reporting: Decimal | None
    current: list[CurrentCompensationOut]
    history: list[HistoryItemOut]  # newest first


# --- country and currency changes (FR-7) ---


class NewAmountIn(BaseModel):
    """The HR-entered amount for one current compensation type, in the new currency,
    per that type's period. Never converted automatically."""

    model_config = ConfigDict(extra="forbid")

    compensation_type_id: int
    amount: Annotated[Money, Field(ge=0)]


class CurrencyChangeIn(BaseModel):
    model_config = ConfigDict(extra="forbid")

    currency: CurrencyCode
    amounts: list[NewAmountIn]  # one per current compensation type
    change_reason_id: int  # any reason from the shared list, e.g. market adjustment
    effective_date: date
    changed_by: NonEmpty
    note: str | None = None


class RelocationIn(BaseModel):
    """Move the employee to another country. Base pay is re-recorded unchanged as a
    "relocation" record, unless `currency` is given too: then every current type is
    re-recorded in it with `amounts`, in the same step."""

    model_config = ConfigDict(extra="forbid")

    country: CountryCode
    effective_date: date
    changed_by: NonEmpty
    note: str | None = None
    currency: CurrencyCode | None = None
    amounts: list[NewAmountIn] | None = None

    @model_validator(mode="after")
    def amounts_go_with_currency(self) -> "RelocationIn":
        if (self.currency is None) != (self.amounts is None):
            raise ValueError("currency and amounts must be given together")
        return self


class ChangeOut(BaseModel):
    employee: EmployeeOut
    records: list[CompensationChangeOut]  # one per type written
